version: '3'
services:
  poll:
    build: ./poll
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "5000:80"
    networks:
      - poll-tier
    depends_on:
      - "redis"
            
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379"
    networks:
      - poll-tier
      - back-tier
            
  worker:
    build: ./worker
    restart: on-failure
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
    networks:
      - back-tier
    depends_on:
      - "db"
      - "redis"
            
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - result-tier
      - back-tier
          
  result:
    build: ./result
    restart: on-failure
    environment:
      - POSTGRES_DB=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=postgres
      - DB_SERVICE=db
    ports:
      - "5001:80"
    networks:
      - result-tier
    depends_on:
      - "db"

volumes:
  db-data:

networks:
  poll-tier:
    driver: bridge
  result-tier:
    driver: bridge
  back-tier:
    driver: bridge